trigger:
  branches:
    include:
      - main
      - dev
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Variable Packages
  - name: buildConfiguration
    value: 'Release'
  - name: projectPath
    value: 'src/**/*.csproj'
  - name: feedName
    value: 'PersonalFeed'
  
  - name: VersionFromTag
    value: '0.0.1-build.$(Build.BuildId)'
  
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
    - name: VersionFromTag
      value: $[ replace(variables['Build.SourceBranchName'], 'v', '') ]

steps:
  - task: UseDotNet@2
    displayName: 'Instalar .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - task: UseDotNet@2
    displayName: 'Instalar .NET 10 SDK'
    inputs:
      packageType: 'sdk'
      version: '10.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restaurar pacotes'
    inputs:
      command: 'restore'
      projects: '$(projectPath)'

  - task: DotNetCoreCLI@2
    displayName: 'Compilar (Build)'
    inputs:
      command: 'build'
      projects: '$(projectPath)'
      arguments: '--configuration $(buildConfiguration) --no-restore -p:Version=$(VersionFromTag)'

  - task: DotNetCoreCLI@2
    displayName: 'Gerar pacote NuGet (Pack)'
    inputs:
      command: 'pack'
      packagesToPack: '$(projectPath)'
      configuration: '$(buildConfiguration)'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'VersionFromTag'

  - task: NuGetAuthenticate@0
    displayName: 'Autenticar NuGet (Azure Artifacts)'
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['Build.SourceBranchName'], 'dev'))

  - script: |
      dotnet nuget push "$(Build.ArtifactStagingDirectory)/**/*.nupkg" \
        --source "https://ademirferreira.pkgs.visualstudio.com/AdobeMPClient/_packaging/PersonalFeed/nuget/v3/index.json" \
        --api-key az \
        --skip-duplicate
    displayName: 'Publicar no Azure Artifacts (Push)'
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['Build.SourceBranchName'], 'dev'))

  - script: |
      dotnet nuget push "$(Build.ArtifactStagingDirectory)/**/*.nupkg" \
        --source https://api.nuget.org/v3/index.json \
        --api-key "$NUGET_KEY" \
        --skip-duplicate
    displayName: 'Publicar no NuGet.org'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    env:
      NUGET_KEY: $(NUGET_API_KEY)